-- MySQL Script generated by MySQL Workbench
-- Fri Jul  2 15:10:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Imss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Imss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Imss` DEFAULT CHARACTER SET utf8 ;
USE `Imss` ;

-- -----------------------------------------------------
-- Table `Imss`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imss`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidoMaterno` VARCHAR(45) NULL,
  `apellidoPaterno` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `NSS` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Imss`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imss`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idmedico`),
  UNIQUE INDEX `idmedico_UNIQUE` (`idmedico` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Imss`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imss`.`sucursal` (
  `idsucursal` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  UNIQUE INDEX `idsucursal_UNIQUE` (`idsucursal` ASC),
  PRIMARY KEY (`idsucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Imss`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imss`.`citas` (
  `enfermedad` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `idUsuario` INT NULL,
  `idMedico` INT NULL,
  `activo` VARCHAR(10) NULL,
  `idSucursal` INT NULL,
  INDEX `fk_idUsuario_idx` (`idUsuario` ASC),
  INDEX `fk_idMedico_idx` (`idMedico` ASC),
  INDEX `fk_idSucursal_idx` (`idSucursal` ASC),
  CONSTRAINT `fk_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Imss`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idMedico`
    FOREIGN KEY (`idMedico`)
    REFERENCES `Imss`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idSucursal`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Imss`.`sucursal` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
